name: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  get-next-version:
    uses: semantic-release-action/next-release-version/.github/workflows/next-release-version.yml@v

  release:
    name: Display the generated versioning.
    runs-on: ubuntu-latest
    if: needs.get-next-version.outputs.new-release-published == 'true'
    needs:
      - get-next-version
    steps:
      - run: echo ${{ needs.get-next-version.outputs.new-release-version }}
  
  #semantic-release:
  #  name: Create the Package Release
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v3 # Need the full commit history for conventional commit
  #  - name: Setup .NET
  #    uses: actions/setup-dotnet@v2
  #    with:
  #      dotnet-version: 6.0.x
  #  - name: Bump version and push tag
  #    id: tag_version
  #    uses: mathieudutour/github-tag-action@v6.0
  #    with:
  #      github_token: ${{ secrets.TOKEN_GITHUB }}
  #  - name: Create a GitHub release
  #    uses: ncipollo/release-action@v1
  #    with:
  #      tag: ${{ steps.tag_version.outputs.new_tag }}
  #      name: Release ${{ steps.tag_version.outputs.new_tag }}
  #      body: ${{ steps.tag_version.outputs.changelog }}
  #  - name: Create Nuget Package
  #    run: dotnet build -c Release ./ZDatabase/ZDatabase.csproj && dotnet pack -c Release -p:PackageVersion=${{ steps.tag_version.outputs.new_version }} -o . ./ZDatabase/ZDatabase.csproj
  #  - name: Upload Package for Publishing
  #    uses: actions/upload-artifact@v3
  #    with:
  #      name: Package
  #      path: ./*.nupkg
